// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Data;

#nullable disable

namespace Schwimmbad_2._4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MyProject.Models.Nutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Besuche")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Punkte")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Nutzer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Besuche = 1,
                            Email = "Max@gmail.com",
                            Name = "Max Mustermann",
                            Punkte = 10
                        },
                        new
                        {
                            Id = 2,
                            Besuche = 1,
                            Email = "Erika@gmail.com",
                            Name = "Erika Mustermann",
                            Punkte = 8
                        },
                        new
                        {
                            Id = 3,
                            Besuche = 1,
                            Email = "John@gmail.com",
                            Name = "John Doe",
                            Punkte = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
